Sections:
  App:
    access-denied:
      en: Access denied. Please sign in
      ru: У вас нет доступа. Пожалуйста, авторизуйтесь
    radar.radarWillStartIn:
      en: 'Radar will start in'
      ru: 'Радар запустится через'
    radar.title:
      en: 'Radar'
      ru: 'Радар'
    radar.tapToSelectTitle:
      en: 'Tap to select the radar location'
      ru: 'Выберите место, где радар будет искать машины'
    radar.timeToSearch:
      en: 'time to search'
      ru: 'время на поиск'
    radar.startSearch:
      en: 'start search'
      ru: 'начало поиска'
    radar.autoBook:
      en: 'book automatically'
      ru: 'авторезервирование'
    radar.currentLocation:
      en: 'Current location'
      ru: 'Текущее место'
    radar.distance:
      en: 'Distance'
      ru: 'Расстояние'
    radar.change:
      en: 'CHANGE'
      ru: 'ИЗМЕНИТЬ'
    radar.confirm:
      en: 'CONFIRM'
      ru: 'ПОДВЕРДИТЬ'
    radar.apply:
      en: 'APPLY'
      ru: 'ПРИМЕНИТЬ'
    radar.back:
      en: 'BACK'
      ru: 'НАЗАД'
    radar.startSearching:
      en: 'Start searching'
      ru: 'Начать поиск'
    radar.specifyLocation:
      en: 'Please specify a location for the radar'
      ru: 'Пожалуйста, укажите местоположение для радара'
    radar.stopSearching:
      en: 'Cancel'
      ru: 'Отменить'
    radar.searching:
      en: 'SEARCHING'
      ru: 'ИЩЕМ'
    radar.repeat:
      en: 'repeat'
      ru: 'Повторять'
    radar.now:
      en: 'NOW'
      ru: 'СЕЙЧАС'
    radar.timeLeft:
      en: 'time left'
      ru: 'осталось времени'
    radar.repeatNever:
      en: 'NEVER'
      ru: 'НИКОГДА'
    radar.repeatEveryMo:
      en: 'Every Monday'
      ru: 'Каждый Понедельник'
    radar.repeatEveryTu:
      en: 'Every Tuesday'
      ru: 'Каждый Вторник'
    radar.repeatEveryWe:
      en: 'Every Wednesday'
      ru: 'Каждую Среду'
    radar.repeatEveryTh:
      en: 'Every Thursday'
      ru: 'Каждый Четверг'
    radar.repeatEveryFr:
      en: 'Every Friday'
      ru: 'Каждый Пятницу'
    radar.repeatEverySa:
      en: 'Every Saturday'
      ru: 'Каждую Субботу'
    radar.repeatEverySu:
      en: 'Every Sunday'
      ru: 'Каждое Воскресенье'
    radar.repeatShortMo:
      en: 'Mo'
      ru: 'Пн'
    radar.repeatShortTu:
      en: 'Tu'
      ru: 'Вт'
    radar.repeatShortWe:
      en: 'We'
      ru: 'Ср'
    radar.repeatShortTh:
      en: 'Th'
      ru: 'Чт'
    radar.repeatShortFr:
      en: 'Fr'
      ru: 'Пт'
    radar.repeatShortSa:
      en: 'Sa'
      ru: 'Сб'
    radar.repeatShortSu:
      en: 'Su'
      ru: 'Вс'
    radar.timeShort.days:
      en: 'd.'
      ru: 'дн.'
    radar.timeShort.hours:
      en: 'h.'
      ru: 'ч.'
    radar.timeShort.minutes:
      en: 'm.'
      ru: 'м.'
    radar.timeShort.seconds:
      en: 's.'
      ru: 'с.'
    common.systemBackButtonTitle:
      en: 'Back'
      ru: 'Назад'
      cs: 'Zpět'
    carview.reservebuttontitle:
      en: 'Reserve'
      ru: 'Забронировать'
      cs: 'Rezervovat'
    car.window.finishrent:
      en: 'Finish rent'
      ru: 'Завершить аренду'
      cs: 'Ukončit pronájem'
    car.window.finishbook:
      en: 'Cancel booking'
      ru: 'Отменить бронь'
      cs: 'Zrušit rezervaci'
    corparative:
      en: 'business'
      ru: 'корпоративный'
      cs: 'business'
    carView.lockButtonTitle:
      en: 'Lock'
      ru: 'Закрыть'
      cs: 'Uzavřít'
    carView.lockButtonSubTitle:
      en: 'and set the parking mode'
      ru: 'и перевести в режим ожидания'
      cs: 'a přepnout do pohotovostního režimu'
    carView.openCarNormalTitle:
      en: 'Open'
      ru: 'Открыть'
      cs: 'Otevřít'
    carView.unlockButtonSubTitle:
      en: 'and start the rent mode'
      ru: 'и перевести в режим аренды'
      cs: 'a převést do režimu pronájmu'
    purchase.bonuses.title:
        en: Purchase bonuses
        ru: Покупка бонусов
        cs: Nákup bonusů
    purchase.bonuses.button.buy:
        en: Buy
        ru: Купить
        cs: Koupit
    purchase.bonuses.current-balance:
        en: Current balance
        ru: Текущий баланс
        cs: Aktuální bilance
    purchase.bonuses.select-package:
        en: Please select one of the bonus packages
        ru: Выберите один из бонусных пакетов
        cs: Vyberte si z bonusových balíčků
    purchase.bonuses.bonuses:
        en: bonuses for
        ru: бонусов за
        cs: bonusy za
    purchase.bonuses.card-line-3:
        en: '{price} {currency}'
    purchase.bonuses.card-line-1:
        en: '{bonuses}'
    purchase.bonuses.description:
        en: You will get {bonuses} bonuses for {money} {currency}. Your discount will be {discount-money} {currency}, that is {discount-percents}%
        ru: Вы получите {bonuses} бонусов за {money} {currency}. Ваша скидка {discount-money} {currency}, что составляет {discount-percents}%
        cs: Získáte {bonuses} bonusy za {money} {currency}. Vaše sleva {discount-money} {currency}, což je {discount-percents}%
    purchase.bonuses.description2:
        en: You will get {bonuses} bonuses for {money} {currency}. You will get {discount-percents}% ({discount-money} {currency}) for free!
        ru: Вы получите {bonuses} бонусов за {money} {currency}. Подарок составит {discount-percents}% ({discount-money} {currency})!
        cs: Získáte {bonuses} bonusy za {money} {currency}. Dárek bude {discount-percents}% ({discount-money} {currency})!
    purchase.bonuses.description3:
        en: ''
        ru: ''
    purchase.bonuses.buy-with-default-card:
        en: Pay with card {default-card-number}
        ru: Оплатить картой {default-card-number}
        cs: Platit kartou {default-card-number}
    purchase.bonuses.buy-with-another-card:
        en: Pay with another card
        ru: Оплатить другой картой
        cs: Platit jinou kartou
    message.box.button.ok:
        en: Ok
        ru: Ок
        cs: Ok
    message.box.button.yes:
        en: Yes
        ru: Да
        cs: Ano
    message.box.button.no:
        en: No
        ru: Нет
        cs: Ne
    message.box.button.cancel:
        en: Cancel
        ru: Отмена
        cs: Zrušení
    purchase.bonuses.buy-bonuses-confirmation:
        en: 'Are you sure you want to buy bonuses?'
        ru: 'Вы уверены, что хотите купить бонусы?'
        cs: 'Jste si jisti, že chcete koupit bonusy?'
    purchase.bonuses.add-card:
        en: 'Add a bank card'
        ru: 'Добавить платёжную карту'
        cs: 'Přidat platební kartu'
    carView.lockButtonSubTitle:
        ru: и перевести в режим парковки
        en: and switch to waiting mode
    qr.scanCode:
        ru: Начать поездку
        en: Start the ride
    technician.carOrganizations.title:
        en: Orgnaizations
        ru: Организации
    technician.viewOrganizations:
        en: 'View organizations'
        ru: 'Организации'
    topup.title:
        en: Top-up
        ru: Пополнение баланса
    topup.sum-description:
        en: This amount will be withdrawed from you bank card
        ru: С вашей банковской карты будет списана следующая сумма
    topup.pay:
        en: Pay
        ru: Оплатить
    topup.subtitle:
        en: Before the ride you need to top-up you account
        ru: Чтобы начать аренду, необходимо внести средства на счёт вашей учётной записи
    topup.subtitle.done:
        en: The payment was successful. Please tap OK button and proceed to car booking
        ru: Оплата прошла успешно. Пожалуйста, нажмите кнопку ОК и перейдите к бронированию авбомобиля
    topup.subtitle.failed:
        en: The payment was unsuccessful. Please try again later
        ru: Не удалось произвести оплату. Пожалуйста, попробуйте ещё раз позже
    topup.ok:
        en: Ok
        ru: Ок
    menu.purchaseBonuses:
        en: Purchase bonuses
        ru: Купить бонусы
    whatsapp_chat_with_support_title:
        en: WhatsApp Chat
        ru: Чат WahtsApp
    appless.button.login:
        en: Log In
        ru: Вход
